### ISSUE TITLE
`matplotlib`の参照先の問題

### ISSUE THREAD

**Issue by Mendo73** [Yutsuro/pytorch-time-series-classification#3]
エラーがあり動きませんでした。 
下記がエラーの内容です。
File "C:\Users\endog\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\matplotlib\backend_bases.py", line 2859, in __init__
    self._nav_stack = cbook._Stack()
AttributeError: module 'matplotlib.cbook' has no attribute '_Stack'. Did you mean: 'Stack'?

self._nav_stack = cbook._Stack()
↑このコードでエラーがはかれていて

self._nav_stack = cbook.Stack()
↑このように書き直したら動きました

**Comment by Yutsuro** [comment]
@Mendo73 
issueありがとうございます、これは`tisc`そのもの問題ではなく、`matplotlib`に関する問題です（エラーメッセージが示しているように、エラーを発しているのは環境にインストールされている`matplotlib`のコードであり、`tisc`のコードではありません。したがって、issueもリネームさせてもらいました。）

この問題は、`matplotlib`がお使いの環境に（異なるバージョンのものが）複数インストールされているがために起こっている問題であると思われます。というのも、インストールされている`matplotlib`と**別の場所にある、異なるバージョンの`matplotlib`を参照しているために**発生しています。仮想環境などで閉じた状態であれば、`matplotlib`は適切な参照をするためこの問題は発生しないはずです。（私の環境ではこの問題は発生しません）

ひとつ確認したいのですが、仮想環境の作成には何を使っていますか？`conda`？`venv`？

**Comment by Mendo73** [comment]
説明ありがとうございます！
今ローカルで動かしているので、そこで問題があると思います。仮想環境作って試してみます。
